name: kit_360
description: Final Yr Flutter Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  google_sign_in: ^5.0.4

  #Notifications
  firebase_messaging: ^10.0.2
  flutter_local_notifications: ^9.0.0
  percent_indicator: ^3.4.0

  #State Management
  provider: ^6.0.1

  #dialogflow for chatbot
#  flutter_dialogflow: ^0.1.3
#  bubble: ^1.2.1
#  intl: ^0.17.0
  
  #Others
  clipboard: ^0.1.3
  url_launcher: ^6.0.8
  # recording words
  #speech_to_text: ^5.1.1
  # floating action button effect
  avatar_glow: ^2.0.1

  flutter_svg: ^0.22.0
  webview_flutter: ^2.0.4
  page_transition: ^2.0.4
  flutter_staggered_grid_view: ^0.4.1
  math_expressions: ^2.2.0
  #geolocator: ^7.0.3
  #torch
  flutter_flashlight: ^1.0.0
  #
  path: ^1.6.4
  sqflite: ^2.0.0+4
  table_calendar: ^3.0.2
  font_awesome_flutter: ^9.1.0
  flutter_slidable: ^0.6.0
  flutter_barcode_scanner: ^2.0.0
  barcode_widget: ^2.0.1
  syncfusion_flutter_gauges:
  fl_chart:
  analog_clock:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/social media/
    - assets/utility/
    - assets/productivity/
    - assets/news/
    - assets/education/
    - assets/health and fitness/
    - assets/shopping and payments/
    - assets/entertainment/
    - assets/extra/
    - assets/med/
#    - assets/kit360chatbot.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
